spring.application.name=demo
spring.mongodb.uri=mongodb://myUserAdmin:Mongoplex.00@ymir.uab.cat:8000/kraken?authSource=admin
#spring.mongodb.uri=mongodb://localhost:27017/kraken

# Segunda conexion Mongo para bibliometria JCR
app.jcr.mongodb.uri=mongodb://myUserAdmin:Mongoplex.00@ymir.uab.cat:8000/JCR?authSource=admin

spring.security.user.name=recerca
spring.security.user.password=UAB

server.port=8080