spring.application.name=demo
spring.mongodb.uri=mongodb://myUserAdmin:Mongoplex.00@ymir.uab.cat:8000/kraken?authSource=admin&serverSelectionTimeoutMS=120000&socketTimeoutMS=120000&connectTimeoutMS=120000
#spring.mongodb.uri=mongodb://localhost:27017/kraken

# Segunda conexion Mongo para bibliometria JCR
app.jcr.mongodb.uri=mongodb://myUserAdmin:Mongoplex.00@ymir.uab.cat:8000/JCR?authSource=admin

spring.security.user.name=recerca
spring.security.user.password=UAB

<<<<<<< HEAD
server.port=8081
=======
app.security.api-key=${API_KEY:sk_uab_2026_9fA7kLm2Qx8pV3tR6nY1cD4eH0jK5mZ}
app.security.api-key-header=X-API-KEY

server.port=8080
>>>>>>> 67287291e73bade2a6158d9e3fc08b6f0709a0bd
